### ISSUE TITLE
Delete Repo?

### ISSUE THREAD

**Issue by srguglielmo** [pantheon-training-org/sguglielmo-drupalcon-seattle-2019#211]
Hi Pantheon Team,

I attended the CI/CD training at DrupalCon Seattle 2019, where this repo was created. Since it's no longer used, can it be deleted? I actually receive daily emails from CircleCI about the build failing, so I'm trying to delete/cleanup the repos.

Thanks!
Steve

**Comment by davidneedham** [comment]
@srguglielmo Yes, no problem. You can go into Circle and tell it to stop trying to build or stop following the build, but I agree these should probably just be deleted.
